#!/bin/sh

mkdir -p "/etc/fchomo/templates/" 2>/dev/null
if [ ! -s "/etc/fchomo/templates/hosts.yaml" ]; then
	cat <<- EOF > "/etc/fchomo/templates/hosts.yaml"
	hosts:
	  # '*.clash.dev': 127.0.0.1
	  # 'alpha.clash.dev': '::1'
	  # test.com: [1.1.1.1, 2.2.2.2]
	  # baidu.com: google.com
	  dns.alidns.com: [223.6.6.6, '2400:3200:baba::1', 223.5.5.5, '2400:3200::1']
	  dns.google: [8.8.8.8, '2001:4860:4860::8888', 8.8.4.4, '2001:4860:4860::8844']
	EOF
fi

if ! uci -q get fchomo.global.authentication; then
	uci add_list fchomo.global.authentication="fchomodef:$(cat /proc/sys/kernel/random/uuid)"
	uci commit fchomo
fi

exit 0
